export const SET_CURRENT_CHAT_PROFILE = "SET_CURRENT_CHAT_PROFILE"

export const SET_CURRENT_CHAT_ID = "SET_CURRENT_CHAT_ID"

export const SET_CHAT_LIST = "SET_CHAT_LIST"

export const SET_MATCH_LIST = "SET_MATCH_LIST"