export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE"

export const EDIT_FIRST_NAME = "EDIT_FIRST_NAME"

export const USER_CURRENT_LOCATION = "USER_CURRENT_LOCATION"

export const SET_PICTURE = "SET_PICTURE"